---
- name: Install etcd
  package:
    name: etcd
    state: present

- name: Configure etcd
  copy:
    dest: /etc/etcd/etcd.conf.yml
    content: |
      name: 'controller'
      data-dir: /var/lib/etcd
      initial-cluster-state: 'new'
      initial-cluster-token: 'etcd-cluster-01'
      initial-cluster: 'controller=http://127.0.0.1:2380'
      initial-advertise-peer-urls: 'http://127.0.0.1:2380'
      advertise-client-urls: 'http://127.0.0.1:2379'
      listen-peer-urls: 'http://127.0.0.1:2380'
      listen-client-urls: 'http://127.0.0.1:2379'
  notify:
    - Restart etcd

- name: Enable and start etcd service
  service:
    name: etcd
    state: started
    enabled: yes
